# Generated by Django 5.0.6 on 2024-06-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizwhiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='number',
            new_name='city',
        ),
    ]
